### ISSUE TITLE
Could AwooOS fit on a floppy?

### ISSUE THREAD

**Issue by informer2016** [duckinator/awooos#29]
Even today the floppies are still being used, for example - as virtual floppies inside the coreboot open source BIOS. Just imagine: your wonderful OS could be a part of someone's BIOS build! _(for coreboot supported motherboard, maybe you have or could get one - see https://www.coreboot.org/Supported_Motherboards )_

If you already have a coreboot-supported motherboard, or a real chance to get one, - wouldn't it be cool to be able to launch your own OS straight from the BIOS chip? ;) With one simple command its possible to add any floppy to coreboot BIOS build - and then you see it as a boot entry! Multiple floppies could be added this way _(as long as you have enough space left inside the BIOS flash chip, luckily LZMA compression could be used for the stored floppies to reduce their occupied size)_

**Comment by duckinator** [comment]
Creating floppy images is more difficult than creating CD images and I'd never use this feature myself, so it'd do nothing but create a maintenance burden.

You also appear to be a bot, posting the same thing verbatim on innumerable repositories. As such, I'm closing this issue.

**Comment by informer2016** [comment]
@duckinator  Sorry, I am not a bot, its' just I did not see any need to rewrite my message "to be unique". I am looking for the best floppy based operating systems to use with this wonderful BIOS. Please let me know if your plans would change - and in any case, I would be curious to see your OS grow

**Comment by duckinator** [comment]
Ah, okay. Sorry if I came across as rude there; I get frustrated with unsolicited feedback from bots, and your account looked like a bot.

If you'd like, I can create

**Comment by duckinator** [comment]
Ah, okay. Sorry if I came across as rude there; I get frustrated with unsolicited comments from bots, and your account looked like a bot.

I'm not opposed to creating a repository which pulls in awooOS as a git submodule and builds a floppy image. That way, it avoids complicating the primary codebase, but floppy images are still a possibility.

But I'd still not be offering any guarantees that it'd remain small enough to support that kind of usage.

**Comment by informer2016** [comment]
@duckinator No problem :) Double size virtual floppies _(2.88 MB / 2949120 bytes instead of 1.44 MB / 1474560 bytes )_ are also supported - and, although my free space at BIOS is just 3 MB, maybe with compression even this "fat floppy" would take significantly less space - so that your OS could fit not instead but together with other wonderful systems :) I wish you Happy New Year 2018 - wondeful life and bugless code ;)
